### PR TITLE
Add head.offline to documentation

### PR DESCRIPTION
**Pull request by lukeramsden**

### CODE REVIEW

**Comment by lukeramsden** [comment]
@gliechtenstein

**Comment by gliechtenstein** [comment]
Wow thanks! One correction: I know this is a bit quirky but on Jasonette, these boolean attributes are interpreted as "true" just by existing. This means, if you say `{"offline": "yes"}`, this will also be interpreted as true. Which also means even `{"offline": "false"}` will be interpreted as true, since it's a non-null value.

To make an attribute "false", you simply don't include them. That's why "offline" is an optional attribute. By default it's false.

That said this needs to be addressed in the future somehow, but for now this is how it works. So I think we need to make a small correction about the `true/false` part. Sorry for the confusion!

**Comment by gliechtenstein** [comment]
Awesome, thank you! 👍

**Comment by gliechtenstein** [comment]
added more with https://github.com/Jasonette/documentation/commit/a4a50dc4e6ee8073f1a3d19232765864ee562e8c

**Pull request merged**
