### PR TITLE
Documentation for ads

### PR DESCRIPTION
**Pull request by lukeramsden**
Solves #20 
@wajahatch888 @gliechtenstein Please check that this is all correct

### CODE REVIEW

**Comment by lukeramsden** [comment]
@gliechtenstein What do you think now?

**Comment by wajahatch888** [comment]
@lukeramsden , Thanks for doing the documentation for the AdMob feature. I was reviewing the documentation and found that you have missed those points which are important to integrate Ads in application. User needs needs to do little more work to show ads.  Following are the steps which are missing.

- Uncomment the `pod 'GoogleMobileAds', '~> 7.8'` and perform `pod install`
- User need to turn on the Ad feature from the code as well. To do this, open `Jasonette > Config > Constants.h` file from XCode, Uncomment the line: `#define ADS 1` (by removing the //).

@gliechtenstein already described [#79](https://github.com/Jasonette/JASONETTE-iOS/issues/79) these steps along with images. You can get a lot of help from it.

**Comment by lukeramsden** [comment]
@wajahatch888 Woops i forgot about that. I'll do that today

**Comment by wajahatch888** [comment]
@lukeramsden Great!

**Comment by lukeramsden** [comment]
Alright @wajahatch888 @gliechtenstein What's the thoughts now?

**Comment by gliechtenstein** [comment]
I think this is looking good! what do you think @wajahatch888 ?

**Comment by wajahatch888** [comment]
@lukeramsden , @gliechtenstein , Yes this looks good. Only one thing which is bothering me that we are referencing `develop` branch instead of `master ` in the documentation ( i know we didn't merge the `develop` in to `master` yet). I think it is the time to merge branches and reference `master` branch in the documentation.

**Comment by gliechtenstein** [comment]
@lukeramsden @wajahatch888 yes I'm going to do this today.

**Comment by gliechtenstein** [comment]
OK Just merged `develop` into `master` so we're all synced up!

Merged. Thanks!

**Pull request merged**
